name: Imprimir secret en dev

on:
  push:
    branches:
      - dev   # Se ejecuta en commits (push) a la rama dev

jobs:
  print-secret:
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - name: Mostrar secret
        run: echo "XDDDDDDDDDDDDDDDDDDDDDDDDDDD"
