name: Imprimir API_KEY en dev

on:
  push:
    branches:
      - dev

jobs:
  print-api-key:
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - name: Mostrar API_KEY
        run: echo "La API_KEY es: ${{ secrets.API_KEY }}"
