name: Imprimir longitud de API_KEY en dev

on:
  push:
    branches:
      - dev

jobs:
  print-api-key:
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - name: Mostrar longitud de API_KEY
        run: echo "La longitud de API_KEY es ${#API_KEY}"
        env:
          API_KEY: ${{ secrets.API_KEY }}

